### ISSUE TITLE
PreventExitingMenu not working

### ISSUE THREAD

**Issue by n00el** [TomGrobbe/MenuAPI#10]
Okay, I have one menu, with only one item, and I have this code:
```
MenuController.MenuAlignment = MenuController.MenuAlignmentOption.Right;
MenuController.PreventExitingMenu = true;
```

The aligment is working, I can set it to the left/to the right, but the PreventExitingMenu not doing anything. I can still exit the menu with the esc button, the backspace etc..

**Comment by TomGrobbe** [comment]
prevent exiting menu is actually incorrectly named, but can't be changed due to backwards compatibility. All it does is prevent opening the pause menu when pressing ESC or P while the menu is open. Use the DisableBackButtons property to disable the ESC/backspace buttons.
