### ISSUE TITLE
Exception during Executing Post callback: NullRefernceException

### ISSUE THREAD

**Issue by GNG2017** [TomGrobbe/MenuAPI#12]
https://github.com/TomGrobbe/MenuAPI/blob/6f2a449a48300bd754bcfc748d9065935c329cf9/MenuAPI/Menu.cs#L1108
![image](https://user-images.githubusercontent.com/25616517/59966096-761e6280-9517-11e9-8a49-9132005b5388.png)
If I create a menu without a subtitle and I put more than 10 MenuItems in it then I get this error constantly if I'm in that menu.

**Comment by TomGrobbe** [comment]
@GNG2017 Good find, never ran into this myself I guess because all my menus have subtitles. I’ll change it later, thank you!

**Comment by TomGrobbe** [comment]
Should be fixed in referenced commit above.
