### ISSUE TITLE
Color.FromArgb issue

### ISSUE THREAD

**Issue by StasiekESX** [TomGrobbe/MenuAPI#13]
![image](https://user-images.githubusercontent.com/42705773/60621404-e5306c80-9ddd-11e9-99c9-426c10b2a201.png)
![image](https://user-images.githubusercontent.com/42705773/60621423-efeb0180-9ddd-11e9-8b0a-9c3588574366.png)
![image](https://user-images.githubusercontent.com/42705773/60621441-f8433c80-9ddd-11e9-9a1c-91094e33a9cf.png)
![image](https://user-images.githubusercontent.com/42705773/60621469-05f8c200-9dde-11e9-9808-ae018bd601d3.png)
![image](https://user-images.githubusercontent.com/42705773/60621482-10b35700-9dde-11e9-87ad-a2ef51e4c3a9.png)

**Comment by TomGrobbe** [comment]
![image](https://user-images.githubusercontent.com/31419184/60621688-99ca8e00-9dde-11e9-823d-a8881d8b4312.png)

![image](https://user-images.githubusercontent.com/31419184/60621717-b4046c00-9dde-11e9-9627-ad5e1981ab2b.png)

works fine

**Comment by TomGrobbe** [comment]
try only using the namespaces i included above, that should work. I've had this issue only when transferring from the old references to the new CFX API set once, but just using the above works fine.

**Comment by StasiekESX** [comment]
![image](https://user-images.githubusercontent.com/42705773/60682728-b9bc8900-9e94-11e9-8ea5-a8fdde7da74f.png)
![image](https://user-images.githubusercontent.com/42705773/60682735-c50fb480-9e94-11e9-9236-4dc1bd9557f4.png)

I had to add Alias to CitizenFX.Core
