### ISSUE TITLE
MenuAPI Exports

### ISSUE THREAD

**Issue by TheDumpap** [TomGrobbe/MenuAPI#17]
Hi!
The system looks great, and I've been experimenting with it for a little bit.
My entire codebase is in JavaScript, and there's really nothing that compares to this API as of yet.
Would it be possible to expose all the functions, events etc. with exports?

If so, is this planned?

**Comment by TomGrobbe** [comment]
There was a wrapper planned, but I never ended up making one. And I'm no longer planning on making it. You'll have to convert it to javascript yourself or switch to C#.
