### ISSUE TITLE
Fix the need to make new ListItems for changing color / opacity

### ISSUE THREAD

**Issue by manups4e** [TomGrobbe/MenuAPI#20]
Hi.. so this is to help you improove MenuAPI.. just set 
BeginScaleformMovieMethod(ColorPanelScaleform, "SET_IS_PC");
ScaleformMovieMethodAddParamBool(true);
EndScaleformMovieMethod();

you can use it on OpacityPanel too

this way you can control the Scaleform directly without the need to make a new ListItem

this is the result
https://i.imgur.com/qmxXfrH.png

Cheers

**Comment by TomGrobbe** [comment]
I don't see what's different about the current panel? it looks exactly the same on your screenshot?

**Comment by manups4e** [comment]
with this let's call it add on you add arrows on the side of the panel.. this way you can control it directly with mouse like in GTA Online

**Comment by TomGrobbe** [comment]
@manups4e Except there are no mouse controls available in MenuAPI. So that seems quite useless.

**Comment by manups4e** [comment]
🤔 well then it's useless for real.. sorry then ^^ i'll close the issue

**Comment by TomGrobbe** [comment]
@manups4e Np, I don’t mind suggestions like this ;)

**Comment by manups4e** [comment]
:) thanks 👍  i was experimenting with scaleforms to give NativeUI new life and i thought you might have wanted this suggestion too :)
