### ISSUE TITLE
How to add an image to the header?

### ISSUE THREAD

**Issue by EleDos** [TomGrobbe/MenuAPI#23]
Hi.
I would like to know how to add an image to the header.
I am new to this and would need some help.
Thank you.

**Comment by TomGrobbe** [comment]
https://github.com/TomGrobbe/MenuAPI/blob/700db477eb26fca9f21995de22dcf51669ce1eca/MenuAPI/Menu.cs#L366

You need to change that for every menu that you want the header to be on. If you want a custom image, you'll need to stream it using a .ytd file, or whatever the texture file for GTA is.

**Comment by EleDos** [comment]
Ok. Two doubts: where in the code line do I write the name of the .ytd file, and where do I put the .ytd file so that it reads it

**Comment by TomGrobbe** [comment]
@EleDos i just explained that.... and the ytd file goes in your stream folder. However, this is more a fivem scripting support question than a MenuAPI question.

**Comment by EleDos** [comment]
Thanks for answering. The truth has been several days looking for how to do this for support forums for fivem and nobody gave me an answer. Sorry for the inconvenience, thanks again.

**Comment by pepper123321** [comment]
What stream folder are you talking anout, there are a lot of them.
