### ISSUE TITLE
Menu opens by pressing M

### ISSUE THREAD

**Issue by natixco** [TomGrobbe/MenuAPI#25]
Hey, I don't have any keybind set to M in my whole code, however when I press that it opens a submenu of a submenu. I've tried by removing the submenu, but then it opens the main menu.

**Comment by TomGrobbe** [comment]
@natixco Set the menu toggle key to -1. The menu toggle key opens the main menu by default. Or if it’s unset, it opens the first menu it finds in all registered menus.

**Comment by natixco** [comment]
Got it, thank you for the fast response!
