### ISSUE TITLE
Any idea?

### ISSUE THREAD

**Issue by DevBiiTz** [TomGrobbe/MenuAPI#28]
I have updated to the latest version and this keeps happening to me, any idea why it is? when you open any menu then you can reopen it by hitting the L key

![image](https://user-images.githubusercontent.com/30190276/82550829-0ebdc800-9b57-11ea-89bf-beab01d3fefb.png)

Thanks for this project <3.

**Comment by DevBiiTz** [comment]
PD: Is RedM Release

**Comment by TomGrobbe** [comment]
Does this also happen with v3.1.1?

**Comment by DevBiiTz** [comment]
yes, it also happened to me in 3.1.1 and that's why I downloaded 3.1.2 today to try but it remains the same

**Comment by TomGrobbe** [comment]
Alright, it seems to crash here: 
![image](https://user-images.githubusercontent.com/31419184/82551874-55b0bb00-9b61-11ea-8031-aa8fe11eb582.png)
Which makes me think that your `MenuController.MainMenu` is null? Did you make a menu and add it using `MenuController.AddMenu()` or `MenuController.AddSubMenu()`?

**Comment by DevBiiTz** [comment]
![image](https://user-images.githubusercontent.com/30190276/82552158-7aa13000-9b59-11ea-8125-efa7bf059a10.png)
using AddMenu

**Comment by TomGrobbe** [comment]
@DevBiiTz and did you make sure that that code is actually executed (for example adding a Debug.WriteLine($"{MenuController.MainMenu.MenuTitle}"); right after MenuController.AddMenu(menuStables);` ?

**Comment by DevBiiTz** [comment]
I will try to see

**Comment by DevBiiTz** [comment]
![image](https://user-images.githubusercontent.com/30190276/82553103-521a3580-9b5b-11ea-9f40-907949fa769e.png)

**Comment by DevBiiTz** [comment]
That error happens from time to time to one in 6 users who connect

**Comment by DevBiiTz** [comment]
also sometimes while you play and you have been doing nothing for a long time this comes out as it just came out right now

![image](https://user-images.githubusercontent.com/30190276/82553209-84c42e00-9b5b-11ea-8288-3bf524207b6a.png)

**Comment by DevBiiTz** [comment]
> also sometimes while you play and you have been doing nothing for a long time this comes out as it just came out right now
> 
> ![image](https://user-images.githubusercontent.com/30190276/82553209-84c42e00-9b5b-11ea-8288-3bf524207b6a.png)

This error repeat every tick and you need reconnect to fix

**Comment by TomGrobbe** [comment]
> > also sometimes while you play and you have been doing nothing for a long time this comes out as it just came out right now
> > ![image](https://user-images.githubusercontent.com/30190276/82553209-84c42e00-9b5b-11ea-8288-3bf524207b6a.png)
> 
> This error repeat every tick and you need reconnect to fix

That's probably a RDR issue that I can't solve, because this crashes:
```
Call(SET_STREAMED_TEXTURE_DICT_AS_NO_LONGER_NEEDED, asset);
```
I'll add a null check for that, as well as the other thing, hopefully that helps but I don't think it will.

---


> ![image](https://user-images.githubusercontent.com/31419184/82555695-89431380-9b68-11ea-981f-a8440e66a76e.png)
> That error happens from time to time to one in 6 users who connect

I've also added null checks for this, which should print an error in the console if the MainMenu is in fact null. So it shouldn't crash, but the menu won't open if you press the button.

---

Here's a direct download link to the version with these changes mentioned above:

https://cdn.discordapp.com/attachments/651445289781297183/712992320965836840/MenuAPI-dev-1.1.81-RedM.zip

Let me know if this helps. Unfortunately RedM does not work for me at all (it crashes either right before or right as I'm about to spawn in on any server) so I won't be able to test anything.

**Comment by DevBiiTz** [comment]
Sorry my bad english.
![image](https://user-images.githubusercontent.com/30190276/82555605-f43c1c80-9b5f-11ea-91ef-169829e9a099.png)
I just checked one thing that when you dump and open the menu with the L key it doesn't make it run, it's like the menu actually hides when closed and then lets you open it again by pressing the L key

Example:
[1] - When i open menu in the shop pressin Enter key
[2] - Once the menu has been opened, I close it using the backspace, I leave the store area and press the L key and the menu is displayed without running the debug.writeline

**Comment by DevBiiTz** [comment]
> > > also sometimes while you play and you have been doing nothing for a long time this comes out as it just came out right now
> > > ![image](https://user-images.githubusercontent.com/30190276/82553209-84c42e00-9b5b-11ea-8288-3bf524207b6a.png)
> > 
> > 
> > This error repeat every tick and you need reconnect to fix
> 
> That's probably a RDR issue that I can't solve, because this crashes:
> 
> ```
> Call(SET_STREAMED_TEXTURE_DICT_AS_NO_LONGER_NEEDED, asset);
> ```
> 
> I'll add a null check for that, as well as the other thing, hopefully that helps but I don't think it will.
> 
> > ![image](https://user-images.githubusercontent.com/31419184/82555695-89431380-9b68-11ea-981f-a8440e66a76e.png)
> > That error happens from time to time to one in 6 users who connect
> 
> I've also added null checks for this, which should print an error in the console if the MainMenu is in fact null. So it shouldn't crash, but the menu won't open if you press the button.
> 
> Here's a direct download link to the version with these changes mentioned above:
> 
> https://cdn.discordapp.com/attachments/651445289781297183/712992320965836840/MenuAPI-dev-1.1.81-RedM.zip
> 
> Let me know if this helps. Unfortunately RedM does not work for me at all (it crashes either right before or right as I'm about to spawn in on any server) so I won't be able to test anything.

Thanks, i got try

**Comment by TomGrobbe** [comment]
> [2] - Once the menu has been opened, I close it using the backspace, I leave the store area and press the L key and the menu is displayed without running the debug.writeline

Well, that sounds like it's fine because you should only create and add the menu once. Don't create a new menu every single time or re-add the same menu multiple times.

**Comment by DevBiiTz** [comment]
The natives' bugs seem fixed,

A friend entered the server after me and hit the L key without first going to the store and this came out
![image](https://user-images.githubusercontent.com/30190276/82556481-b213da80-9b61-11ea-9a1c-3dc13ad435c8.png)

**Comment by TomGrobbe** [comment]
> The natives' bugs seem fixed,
> 
> A friend entered the server after me and hit the L key without first going to the store and this came out

Yes, that's because you haven't added a menu yet. You have to make sure there is a MainMenu set before someone can press the button to toggle the menu.

**Comment by DevBiiTz** [comment]
> > The natives' bugs seem fixed,
> > A friend entered the server after me and hit the L key without first going to the store and this came out
> 
> Yes, that's because you haven't added a menu yet. You have to make sure there is a MainMenu set before someone can press the button to toggle the menu.

Thank you very much for your help 😃 

I understand, these menus are for a store that are in a location and I would like to disable the menu key, is there any right way or do I have to do it under an edited version ?

**Comment by TomGrobbe** [comment]
Yes, you can set it to -1 or something like that using:
```
MenuController.MenuToggleKey = (Control)-1;
```

**Comment by TomGrobbe** [comment]
And don't forget to disable the controller keybind as well:
```
MenuController.EnableMenuToggleKeyOnController = false;
```
