### ISSUE TITLE
[enhancement] Add new NativeUI features

### ISSUE THREAD

**Issue by manups4e** [TomGrobbe/MenuAPI#6]
For sure u know that in LUA the most complete menu wrapper is this https://github.com/iTexZoz/NativeUILua-Reloaded

i was thhinking if you could add some cool features like heritage panel / timebars / custom banner sprites and / or (like in Guad's NativeUI, fivem branch) ability to change the menu position offset

anyway thx for the awesome Word you did!!

**Comment by TomGrobbe** [comment]
>ability to change the menu position offset

Probably won't be added because it aligns to the safezone so that it'll always appear at the right position for _all_ resolutions and aspect ratios. Offset would have to be different for every resolution/aspect ratio and I'm not going to hardcode that.

> custom banner sprites

That's already a feature...

>Heritage panel

Also probably not going to be added because there's 40 something parents, and only 20 something images. So it's completely useless.

> timebars

ehm, how is this related to a _menu_ exactly? This seems more suited for some general "UI/HUD" API, not a MenuAPI, but I'll consider this.

**Comment by manups4e** [comment]
why not the heritage? 
if i want to make a char creation menu without this is impossible... 
https://github.com/iTexZoz/NativeUILua-Reloaded/blob/master/UIMenu/windows/UIMenuHeritageWindow.lua

could be great to add more panels too
https://github.com/iTexZoz/NativeUILua-Reloaded/tree/master/UIMenu/panels
like the Grid Panel, Statistic Panel etc

**Comment by TomGrobbe** [comment]
>Also probably not going to be added because there's 40 something parents, and only 20 something images. So it's completely useless.

**Comment by manups4e** [comment]
if you enumerate parents there are 23 dads and 22 mothers.. i can even give you the names taken from game files as i used them in LUA with that menu wrapper..

**Comment by TomGrobbe** [comment]
Nope, there's actually no specific difference between male/female parents, so there's an equal amount of dads vs moms. (40 something including DLC parents). So this means you'd have to restrict players in only using half of that for dads/moms.

Seeing that I have almost no time at all lately, I just can't implement this. There's many other things just way up there on my todo list and this is currently just not my priority. Maybe sometime in the future, but _at least_ not anytime soon.

**Comment by manups4e** [comment]
i see :) do you accept pull requests? i might try it myself.. + add-on panels (grid, stats)

**Comment by TomGrobbe** [comment]
I do, but I am very picky and usually require at least one change (usually more) before its merged. Just because I feel like it should be implemented in a 'generic' way all across the API.

**Comment by manups4e** [comment]
well of course i'll try to do it this way.. if i change something in an API it MUST be generically easily available

**Comment by manups4e** [comment]
you can test it yourself first before of course XD
