### ISSUE TITLE
Is there a MenuAPI.dll reference?

### ISSUE THREAD

**Issue by BobbyTheDev** [TomGrobbe/MenuAPI#7]
Hey I'm just looking for a MenuAPI.dll reference, haven't found one yet.

**Comment by TomGrobbe** [comment]
you're trying to do what exactly?

**Comment by BobbyTheDev** [comment]
Nothing but I have a problem with the menu, it keeps saying that System.Drawing and CitizenFX.core.dll keep interfering with Colors, you know how to fix that?

**Comment by BobbyTheDev** [comment]
Also the documentation doesn't tell me anything.

**Comment by BobbyTheDev** [comment]
Fixed it you have to add the Citizen.Core.Client.dll to fix some stuff

**Comment by TomGrobbe** [comment]
no you don't, don't do that that's wrong. Just download the NuGet packages that are already installed when you first open it... Also add System.Drawing.dll if that's not added for some reason.
