### ISSUE TITLE
"The type "color" exists in both System.Drawing and CitizenFX.Core" Fix?

### ISSUE THREAD

**Issue by BobbyTheDev** [TomGrobbe/MenuAPI#8]
Anyone know how to fix this error?

**Comment by Syntasu** [comment]
You can tell which class maps to which namespace via the `using` syntax:

```cs
using Color = System.Drawing;
//or
using Color = CitizenFX.Core;
```

This should get the rid of the ambiguous namespace naming.

**Comment by BobbyTheDev** [comment]
which one should I use for slider coloring?

**Comment by BobbyTheDev** [comment]
Keep getting an error saying "FromArgb namespace does not exist in the namespace CitizenFX/System.Drawing"

**Comment by TomGrobbe** [comment]
Add `System.Drawing` as a reference.

**Comment by TomGrobbe** [comment]
Don't just add `using System.Drawing;` but actually add it in the references window.

**Comment by BobbyTheDev** [comment]
I did, still doesn't work.

**Comment by TomGrobbe** [comment]
using visual studio 2017 or 2019?

**Comment by BobbyTheDev** [comment]
2017

**Comment by TomGrobbe** [comment]
Try vs2019, that's the last version I used to make sure that it works.

**Comment by BobbyTheDev** [comment]
I have to re-install visual studio?

**Comment by BobbyTheDev** [comment]
Yeah but if I do that then normal scripting doesn't work, for like GTA5.

**Comment by TomGrobbe** [comment]
No, just visual studio 2019 if you haven't got that already. should work on 2017 but maybe there's some weird race condition preventing your 2017 version to work properly.

**Comment by BobbyTheDev** [comment]
Okay, installing it now. Do you have a discord where we could talk better?

**Comment by TomGrobbe** [comment]
vespura.com/discord

**Comment by BobbyTheDev** [comment]
thanks
